//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentableBeer
    {
        public int BeerId { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public string BeerType { get; set; }
        public Nullable<int> BeerRating { get; set; }
    }
}
